### ISSUE TITLE
LINK method

### ISSUE THREAD

**Issue by pashkevich-d** [MisterMCman/talentengine#29]
@emochris  LINK and UNLINK are no longer part of HTTP, so I can't send LINK requests through the app. We need other implementation for API features which use LINK, first of all to provide images for objects and networks.

**Comment by emochris** [comment]
Idea: Provide a method=LINK/UNLINK as URL parameter by using PUT (or other?)
/api/user?method=LINK

Would this be a good workaround @pashkevich-d ?

**Comment by pashkevich-d** [comment]
@emochris  yes, sounds good. Please let me know when i can test it.

**Comment by emochris** [comment]
@pashkevich-d  should work now.

**Comment by pashkevich-d** [comment]
@emochris I wrote you on Slack
