### ISSUE TITLE
Implement an invitation message

### ISSUE THREAD

**Issue by PMVyatkin** [MisterMCman/talentengine#99]

**Comment by PMVyatkin** [comment]
When we invite a user somewhere we can add an invitation message (130 smb?).

**Comment by PMVyatkin** [comment]
We have ability to send a message when we add ourselves to a team.

**Comment by PMVyatkin** [comment]
We we follow someone we need to make a message - @PMVyatkin ask Chris about that

**Comment by MisterMCman** [comment]
We have for applying to a network. Maybe we can reuse this.

**Comment by emochris** [comment]
No. Every message is meant to be sent via a preferred messenger like Signal or Whatsapp. The only way for sending systemic messages is eMail but there is no receiving endpoint.

**Comment by PMVyatkin** [comment]
Ok, no invitation messages within JMT.
